import styles from './About.module.css'

const About = () => {
    return (
        <div className="container is-fluid is-flex is-justify-content-center is-align-items-center is-flex-direction-column mt-3">
            <h1 className="title is-3">Acerca de "La Galeria"</h1>
            <div className={`is-flex is-justify-content-center is-flex-direction-column ${styles.paragraph}`}>
                <p className="has-text-justified mb-5">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus facilisis nunc non aliquam lobortis. Aenean in mi eget orci pellentesque efficitur. Curabitur vehicula, purus in porta cursus, dolor est porta augue, eget gravida ante leo eget tellus. Etiam sagittis tortor ac hendrerit rhoncus. Mauris tincidunt eu est nec suscipit. Praesent rutrum sem lectus, non consectetur lacus lacinia ac. Donec ut vulputate turpis. Vestibulum ac dui at ligula egestas posuere in id purus. Nulla aliquet volutpat pellentesque.</p>
                <p className="has-text-justified mb-5">Cras eu neque leo. Vivamus vel placerat lectus. Vestibulum cursus at mi at venenatis. Proin elit nulla, vestibulum tincidunt hendrerit eget, efficitur ut mauris. Mauris interdum, nisi sed pellentesque ultricies, ligula justo cursus diam, sed rutrum magna purus sit amet magna. Cras sapien lorem, maximus at malesuada eu, malesuada non turpis. Sed scelerisque fringilla suscipit. Aenean consectetur cursus dui, et auctor ex condimentum quis. Ut pretium turpis in blandit porttitor. Duis mattis elementum dolor quis varius. Suspendisse volutpat, dolor at bibendum tempor, ipsum nunc tempus elit, eu maximus tellus turpis sit amet diam. Ut laoreet tortor in metus eleifend, auctor aliquam erat rutrum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer vitae libero porttitor, viverra lectus non, viverra felis.</p>
                <p className="has-text-justified mb-5">Etiam fermentum, urna nec efficitur euismod, ligula quam tempor enim, eget porttitor orci eros egestas nisl. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Pellentesque facilisis urna vitae sagittis ultrices. Ut nunc lacus, finibus at mi quis, tincidunt viverra nibh. Etiam blandit enim in ultricies sollicitudin. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aenean cursus eu enim id rhoncus. Ut at congue neque, eu rutrum elit.</p>
                <p className="has-text-justified mb-5">Donec ac hendrerit elit. Vestibulum sodales dignissim maximus. Nulla placerat urna ac risus accumsan dictum. Aliquam sodales lobortis mauris, at ornare metus euismod nec. Etiam pretium ante at consequat fringilla. Aenean imperdiet enim id lacus mollis, eget bibendum nisl fermentum. Curabitur ut est ut diam pretium pellentesque. Etiam ac magna non augue commodo sollicitudin quis eget lorem. Aliquam vitae urna mauris. Phasellus at quam rhoncus, vehicula ligula vel, lacinia libero. Suspendisse at auctor tortor. Donec lacinia purus facilisis massa semper bibendum. Duis sit amet elit consequat, faucibus lacus vitae, varius erat. Praesent nec dictum tortor, vel faucibus dolor.</p>
                <p className="has-text-justified mb-5">Nunc sit amet malesuada justo, non mollis enim. Etiam ultricies dui eleifend ipsum sagittis, sed molestie odio sollicitudin. Nulla auctor metus et urna consectetur dictum. Fusce et augue volutpat, tempor elit quis, sodales felis. Phasellus rhoncus purus ut condimentum faucibus. Maecenas suscipit enim risus, quis tristique leo tempor ac. Nulla vel quam ornare, lobortis neque et, interdum ex. Nam scelerisque, elit at vehicula ultricies, nisl odio vulputate ante, sed viverra orci ligula sed tortor. Etiam sit amet massa a neque aliquet malesuada. In finibus sem nisi, in venenatis sapien commodo eget. Pellentesque tincidunt sit amet ex sit amet dictum. Sed imperdiet sagittis varius. Ut fermentum tellus consectetur varius congue. Suspendisse pulvinar turpis orci, non interdum elit sodales eget. Donec volutpat viverra purus id imperdiet. Proin accumsan ante et tincidunt facilisis.</p>
            </div>
        </div>
    )
}

export default About